#!/bin/bash

# Alfredo H. Locht

# halocht@gmail.com ahlocht@dons.usfca.edu

# This is a QC script to extract the SRA numbers from some fastq files and then process them further

# Script's name: QCfastq_week06

echo "Checking the value of BLASTDB variable"

if [ -z ${BLASTDB} ]; then source /home/.bashrc; export PATH; export BLASTDB; fi

echo "BLASTDB checked"

echo "##################################################"

echo "Downloading fastq files"
